name: jidoapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^6.1.0 # For displaying the map
  latlong2: ^0.9.1 # For latitude and longitude
  shared_preferences: ^2.2.3 # For persistent storage
  provider: ^6.1.2 # For state management
  geojson_vi: ^2.2.5 # Updated version as per suggestion

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add this section for assets
  assets:
    - assets/custom.geo.json # Ensure this path is correct